Imageviewer react images
FlockOfBirds/image-viewer pull request #1
Opened 2017-06-20 06:14 UTC by akileng56

- Display image in light box when clicked
- Zoom in and out
- Unit tests

2017-06-20 09:35 UTC, edwinmp requested changes
Not done. Will complete when I get back from the embassy.

2017-06-20 09:35 UTC, edwinmp commented on Gruntfile.js
> +    const webpackLoaderOptionsPlugin = currentWebpackConfig.plugins.slice(0);
Use webpack-merge instead.

```
"use strict";
const webpack = require("webpack");
const webpackConfig = require("./webpack.config");
const merge = require("webpack-merge");

const webpackConfigRelease = [];
webpackConfig.forEach(function(config) {
    webpackConfigRelease.push(merge(config, {
        plugins: [ new webpack.optimize.UglifyJsPlugin() ]
    }));
});
```

2017-06-20 09:35 UTC, edwinmp commented on Gruntfile.js
> +                    append: "\n\n//# sourceURL=ImageViewer.webmodeler.js\n",
Use `pkg.widgetName` variable. Same with the line below this.

2017-06-20 09:35 UTC, edwinmp commented on package.json
> +  "widgetName": "imageviewer",
Must be upper camel case. `ImageViewer`

2017-06-20 09:35 UTC, edwinmp commented on package.json
> +  "description": "Display an image from specifed source",
... from a specified source

2017-06-20 09:35 UTC, edwinmp commented on package.json
> +    "emit": "tsc",
Repetition of pretest. Remove.

2017-06-20 09:35 UTC, edwinmp commented on package.json
> +    "url": "https://github.com/mendixlabs/slider"
Update URL...

2017-06-20 09:35 UTC, edwinmp commented on package.json
> +    "url": "https://github.com/mendixlabs/slider/issues"
Update URL...

2017-06-20 09:35 UTC, edwinmp commented on src/ImageViewer.xml
> +    <description>Change a number value using a slider</description>
Incorrect description. Match with package.json.

2017-06-20 09:35 UTC, edwinmp commented on src/ImageViewer.xml
> +            <description></description>
Shorten as `<description/>`

2017-06-20 09:35 UTC, edwinmp commented on src/ImageViewer.xml
> +            <caption>System image</caption>
This field is not required since the image URL is to be generated from the context object with no dependency on an attribute.

2017-06-20 09:35 UTC, edwinmp commented on src/ImageViewer.xml
> +            </enumerationValues>
Naming can be improved, and options reduced... Perhaps: context, URL, static.
Whether to use the URL attribute or the static field can be determined based on which option is provided, with the URL attribute taking precedence.

2017-06-20 09:35 UTC, edwinmp commented on src/ImageViewer.xml
> +        <property key="imageAttribute" type="attribute" required="false" isPath="optional" pathType="reference">
If suggested DS options are implemented, rename this to urlAttribute.

2017-06-20 09:35 UTC, edwinmp commented on src/ImageViewer.xml
> +            <caption>Dynamic URL</caption>
Attribute captions must reflect that it's an attribute. e.g Dynamic URL attribute...

2017-06-20 09:35 UTC, edwinmp commented on src/ImageViewer.xml
> +        <property key="static_Url" type="string" required="false">
Stick to camel case. `staticUrl`

2017-06-20 09:35 UTC, edwinmp commented on src/ImageViewer.xml
> +            <caption>Static URL</caption>
Can just have it as URL. It's being static is apparent. Suggestion.

2017-06-20 09:35 UTC, edwinmp commented on src/ImageViewer.xml
> +        <property key="static_Image" type="image" required="false">
Camel case.

2017-06-20 12:54 UTC, edwinmp requested changes

2017-06-20 12:54 UTC, edwinmp commented on src/components/ImageViewer.ts
> +
Remove space.

2017-06-20 12:54 UTC, edwinmp commented on src/components/ImageViewer.ts
> +        return DOM.div({ className: "widget-image-viewer", style: divStyle },
New line before this...

2017-06-20 12:54 UTC, edwinmp commented on src/components/ImageViewer.ts
> +            }),
Can inline these.

2017-06-20 12:54 UTC, edwinmp commented on src/components/ImageViewer.ts
> +    }
Make openLightBox & closeLightBox into single function... can be called toggleLightBoxVisibility or something.

2017-06-20 12:54 UTC, edwinmp commented on src/components/ImageViewerContainer.ts
> +            widthUnits: this.props.widthUnit
Can destructure all these and reduce this to two lines...
```
const { height, heightUnit, width, widthUnit } = this.props;
return createElement(ImageViewer, { height, heightUnits, imageurl: this.state.imageUrl, width, widthUnits });
```

Destructure the state too to make it cleaner, and of course synchronize your naming... Why have heightUnit in one place and heightUnits in another? It's units.

2017-06-20 12:54 UTC, edwinmp commented on src/components/ImageViewerContainer.ts
> +        if (this.subscriptionHandle) window.mx.data.unsubscribe(this.subscriptionHandle);
Andries doesn't like if statements that are not in curly braces.

2017-06-20 12:54 UTC, edwinmp commented on src/components/ImageViewerContainer.ts
> +        if (this.subscriptionHandle) window.mx.data.unsubscribe(this.subscriptionHandle);
Same here.

2017-06-20 12:54 UTC, edwinmp commented on src/components/ImageViewerContainer.ts
> +            message = "Configuration error: for data source Dynamic URL; Dynaic URL attribute is required";
You are still using imageAttribute? Thought we agreed it's not required. As far as I can see, urlAttribute is only being used for conditional checks in this file.

Typo here... Dynaic.

2017-06-20 12:54 UTC, edwinmp commented on src/components/ImageViewerContainer.ts
> +                imageUrl: mxObject.get(this.props.imageAttribute) as string,
Conditional is checking against urlAttribute but you're retrieving from imageAttribute.

2017-06-20 12:54 UTC, edwinmp commented on src/components/ImageViewerContainer.ts
> +            this.setState({
Repetitive code... Extract into function ...

```
private updateUrl(url) {
this.setState{ imageUrl: url, isLoading: false }
}
```

2017-06-20 12:54 UTC, edwinmp commented on src/components/__tests__/ImageViewer.spec.ts
> +
Remove space.

2017-06-20 12:54 UTC, edwinmp commented on src/components/__tests__/ImageViewer.spec.ts
> +    it("renders the lightbox when image is clicked", () => {
... when the image is ...

2017-06-20 12:54 UTC, edwinmp commented on src/components/__tests__/ImageViewer.spec.ts
> +    it("closes the lightbox when close icon is clicked", () => {
... the close icon is ...

2017-06-20 12:54 UTC, edwinmp commented on src/components/__tests__/ImageViewer.spec.ts
> +        it("% when height or width units is set to percentage", () => {
Should these be separated? Not sure... ask Andries?

2017-06-20 12:54 UTC, edwinmp commented on src/components/__tests__/ImageViewer.spec.ts
> +            expect(imageViewer).toBeElement(
Can't you just check for the style properties of the img element without checking the whole thing again?

2017-06-20 12:54 UTC, edwinmp commented on src/components/__tests__/ImageViewer.spec.ts
> +                imageViewer.state().isOpen && createElement(Lightbox, {
You don't need the conditional... Just add what you expect.

2017-06-20 14:44 UTC, akileng56 commented on src/components/__tests__/ImageViewer.spec.ts
> +            expect(imageViewer).toBeElement(
Enzyme cant test style on shallow render

2017-06-20 14:44 UTC, akileng56 commented on src/components/__tests__/ImageViewer.spec.ts
> +    it("closes the lightbox when close icon is clicked", () => {
done

2017-06-20 14:45 UTC, akileng56 commented on src/components/__tests__/ImageViewer.spec.ts
> +    it("renders the lightbox when image is clicked", () => {
done

2017-06-20 14:45 UTC, akileng56 commented on src/components/__tests__/ImageViewer.spec.ts
> +                imageViewer.state().isOpen && createElement(Lightbox, {
Changed

2017-06-20 14:45 UTC, akileng56 commented on src/components/__tests__/ImageViewer.spec.ts
> +
Removed

2017-06-20 14:45 UTC, akileng56 commented on src/components/ImageViewerContainer.ts
> +            this.setState({
Created new function

2017-06-20 14:45 UTC, akileng56 commented on src/components/ImageViewerContainer.ts
> +                imageUrl: mxObject.get(this.props.imageAttribute) as string,
Fixed it

2017-06-20 14:45 UTC, akileng56 commented on src/components/ImageViewerContainer.ts
> +            message = "Configuration error: for data source Dynamic URL; Dynaic URL attribute is required";
Fixed it

2017-06-20 14:46 UTC, akileng56 commented on src/components/ImageViewerContainer.ts
> +        if (this.subscriptionHandle) window.mx.data.unsubscribe(this.subscriptionHandle);
changed

2017-06-20 14:46 UTC, akileng56 commented on src/components/ImageViewerContainer.ts
> +        if (this.subscriptionHandle) window.mx.data.unsubscribe(this.subscriptionHandle);
changed

2017-06-20 14:46 UTC, akileng56 commented on src/components/ImageViewerContainer.ts
> +            widthUnits: this.props.widthUnit
Done

2017-06-20 14:46 UTC, akileng56 commented on src/components/ImageViewer.ts
> +    }
Done

2017-06-20 14:47 UTC, akileng56 commented on src/components/ImageViewer.ts
> +            }),
I think its more readable when its like that

2017-06-20 14:47 UTC, akileng56 commented on src/components/ImageViewer.ts
> +        return DOM.div({ className: "widget-image-viewer", style: divStyle },
Added

2017-06-20 14:47 UTC, akileng56 commented on src/components/ImageViewer.ts
> +
Removed

2017-06-20 14:47 UTC, akileng56 commented on src/ImageViewer.xml
> +        <property key="static_Image" type="image" required="false">
Fixed

2017-06-20 14:47 UTC, akileng56 commented on src/ImageViewer.xml
> +            <caption>Static URL</caption>
changed

2017-06-20 20:14 UTC, Andries-Smit requested changes
Code reviewed, function still needs to be reviewed

2017-06-20 20:14 UTC, Andries-Smit commented on Gruntfile.js
> +            sourceFiles: {
no need for this

2017-06-20 20:14 UTC, Andries-Smit commented on Gruntfile.js
> +                files: [ "./dist/tmp/src/**/*" ],
should watch ` "./src/**/*"`

2017-06-20 20:14 UTC, Andries-Smit commented on Gruntfile.js
> +            source: {
no need for this

2017-06-20 20:14 UTC, Andries-Smit commented on README.md
> +Displays an image on lightbox when image is clicked.
Not proper English: "Display an image on click enlarge the image mobile friendly." or something like this.

2017-06-20 20:14 UTC, Andries-Smit commented on README.md
> +# ImageViewer
split word in 2

2017-06-20 20:14 UTC, Andries-Smit commented on README.md
> +* Support zoom in and out on image.
Click actions: Zoom

2017-06-20 20:14 UTC, Andries-Smit commented on README.md
> + - widget will pick image from context object (context object should inherit from system.image entity).
`The widget`

2017-06-20 20:14 UTC, Andries-Smit commented on README.md
> +   ### Data source: Static image
remove space before ###

2017-06-20 20:14 UTC, Andries-Smit commented on README.md
> +  - On the Data source option of the Data source tab, select the static url
URL is an acronym, in normal sentences they should be all capitals

2017-06-20 20:14 UTC, Andries-Smit commented on README.md
> +  - Specify the url that points to the image (url outside of the mendix system).
Mendix with a capital

2017-06-20 20:14 UTC, Andries-Smit commented on README.md
> +   ### Data source: Static image
remove space before ###

2017-06-20 20:14 UTC, Andries-Smit commented on README.md
> +## Development
May the development guide should be removed from the readme and placed in a different file.

2017-06-20 20:14 UTC, Andries-Smit commented on README.md
> +    grunt
We should look at the standard npm script, the grunt is more an implementation detail, could be gulp or webpack at an other moment, we could generalize it with all packages

2017-06-20 20:14 UTC, Andries-Smit commented on karma.conf.js
> +Object.assign(webpackConfig, {
We could use the `const merge = require("webpack-merge");`

2017-06-20 20:14 UTC, Andries-Smit commented on package.json
> +  "description": "Display an image in a lightbox when the image is clicked",
Update with the improved readme description

2017-06-20 20:14 UTC, Andries-Smit commented on package.json
> +    "lint": "tslint -c tslint.json '**/*.ts' '**/*.tsx' --exclude '**/node_modules/**'"
remove `tsx` unless you use  it in you project, exclude your dist folder too

2017-06-20 20:14 UTC, Andries-Smit commented on package.json
> +  "repository": {
Add pre-push running the unit tests?

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.webmodeler.ts
> +    if (valueMap.source === "urlAttribute") {
could be an `else if` when checking for the same attribute.
It more efficient, same for statement below

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.webmodeler.ts
> +export function getVisibleProperties(valueMap: any, visibilityMap: any) {
Please use typings.
```
type VisibilityMap = {
    [P in keyof ImageViewerContainerProps]: boolean;
};
export function getVisibleProperties(valueMap: ImageViewerContainerProps, visibilityMap: VisibilityMap) {
```
Does not work for nested object but it work for the flat ones.

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.xml
> +    <name>ImageViewer</name>
Add space `Image viewer` they are 2 words, Mendix user is not use to camelCasing / PascalCasing

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.xml
> +    <icon>
Make single line `<icon>....base64...</icon>`

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.xml
> +    <description>Display an image in a lightbox when the image is clicked</description>
Update with new description of readme.md

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.xml
> +                <enumerationValue key="staticImage">Static Image</enumerationValue>
Move this option after `System image`

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.xml
> +            <description>Image url based on context</description>
`Image URL based on context string attribute`

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.webmodeler.ts
> +            return createElement(Alert, { message: warnings });
Always show the warning and the preview when possible.

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.xml
> +            <description>The url of the external image</description>
`URL` Should this be a full URL or could this also be a relative URL?

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.xml
> +        <property key="widthUnit" type="enumeration" defaultValue="pixels">
Default should be `100%` width, height `auto`

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.xml
> +            <description>Maximum width of the image in pixels.</description>
No period at end of description

2017-06-20 20:14 UTC, Andries-Smit commented on src/ImageViewer.xml
> +            <description>No inline style will be set on auto. Percentage is relative to parent container only when parent has an absolute height.</description>
Not sure if that is true `Percentage is relative to parent` is % on image it self or the container around it?

2017-06-20 20:14 UTC, Andries-Smit commented on src/ui/ImageViewer.css
> +    object-fit: contain;
What does ` object-fit: contain;` doe and is it cross browser compatible?

2017-06-20 20:14 UTC, Andries-Smit commented on tsconfig.json
> +    "noImplicitAny": true,
Option `strict`  Enable all strict type checking options. 
Enabling --strict enables --noImplicitAny, --noImplicitThis, --alwaysStrict and --strictNullChecks.

2017-06-20 20:14 UTC, Andries-Smit commented on src/components/ImageViewerContainer.ts
> +            return DOM.div(null,
All rendering should be done in `ImageViewer.ts` except for the error message

2017-06-21 09:19 UTC, akileng56 commented on Gruntfile.js
> +                files: [ "./dist/tmp/src/**/*" ],
Fixed it

2017-06-21 09:20 UTC, akileng56 commented on Gruntfile.js
> +            sourceFiles: {
Removed

2017-06-21 09:20 UTC, akileng56 commented on Gruntfile.js
> +            source: {
Removed

2017-06-21 09:20 UTC, akileng56 commented on README.md
> +# ImageViewer
Done

2017-06-21 09:21 UTC, akileng56 commented on README.md
> +Displays an image on lightbox when image is clicked.
Display an image and enlarge it on click

2017-06-21 09:22 UTC, akileng56 commented on README.md
> +* Support zoom in and out on image.
Support zoom actions

2017-06-21 09:22 UTC, akileng56 commented on README.md
> + - widget will pick image from context object (context object should inherit from system.image entity).
Added

2017-06-21 09:22 UTC, akileng56 commented on README.md
> +  - On the Data source option of the Data source tab, select the static url
Changed

2017-06-21 09:22 UTC, akileng56 commented on README.md
> +  - Specify the url that points to the image (url outside of the mendix system).
Done

2017-06-21 09:23 UTC, akileng56 commented on README.md
> +   ### Data source: Static image
Removed

2017-06-21 09:23 UTC, akileng56 commented on README.md
> +   ### Data source: Static image
Removed

2017-06-21 09:23 UTC, akileng56 commented on karma.conf.js
> +Object.assign(webpackConfig, {
Can't seem to get this working

2017-06-21 09:24 UTC, akileng56 commented on package.json
> +  "description": "Display an image in a lightbox when the image is clicked",
Updated

2017-06-21 09:24 UTC, akileng56 commented on package.json
> +    "lint": "tslint -c tslint.json '**/*.ts' '**/*.tsx' --exclude '**/node_modules/**'"
Removed

2017-06-21 09:24 UTC, akileng56 commented on package.json
> +  "repository": {
Added

2017-06-21 09:24 UTC, akileng56 commented on src/ImageViewer.webmodeler.ts
> +            return createElement(Alert, { message: warnings });
Done

2017-06-21 09:24 UTC, akileng56 commented on src/ImageViewer.webmodeler.ts
> +    if (valueMap.source === "urlAttribute") {
Done

2017-06-21 09:25 UTC, akileng56 commented on src/ImageViewer.webmodeler.ts
> +export function getVisibleProperties(valueMap: any, visibilityMap: any) {
Added typimgs

2017-06-21 09:25 UTC, akileng56 commented on src/ImageViewer.xml
> +    <name>ImageViewer</name>
Added

2017-06-21 09:26 UTC, akileng56 commented on src/ImageViewer.xml
> +    <description>Display an image in a lightbox when the image is clicked</description>
Updated

2017-06-21 09:27 UTC, akileng56 commented on src/ImageViewer.xml
> +    <icon>
Done

2017-06-21 09:27 UTC, akileng56 commented on src/ImageViewer.xml
> +                <enumerationValue key="staticImage">Static Image</enumerationValue>
Moved it

2017-06-21 09:28 UTC, akileng56 commented on src/ImageViewer.xml
> +            <description>Image url based on context</description>
Done

2017-06-21 09:37 UTC, akileng56 commented on src/ImageViewer.xml
> +            <description>The url of the external image</description>
full URL

2017-06-21 09:38 UTC, akileng56 commented on src/ImageViewer.xml
> +        <property key="widthUnit" type="enumeration" defaultValue="pixels">
Done

2017-06-21 10:04 UTC, akileng56 commented on src/ui/ImageViewer.css
> +    object-fit: contain;
Yes it is..used analysis from the canisue site

2017-06-21 19:26 UTC, Andries-Smit commented on src/ImageViewer.webmodeler.ts
> +        if (props.source === "staticImage") {
should be a `else if`

2017-06-22 05:22 UTC, Andries-Smit commented on src/components/ImageViewer.ts
> +        return DOM.div({
Incorrect inenting, move  { to new line

2017-06-23 08:14 UTC, Andries-Smit commented on src/ui/ImageViewer.css
> +    object-fit: contain;
Does not work IE nor Edge https://developer.mozilla.org/nl/docs/Web/CSS/object-fit#Browser_compatibility

2017-06-23 08:17 UTC, akileng56 commented on Gruntfile.js
> +    const webpackLoaderOptionsPlugin = currentWebpackConfig.plugins.slice(0);
Done

2017-06-23 08:17 UTC, akileng56 commented on Gruntfile.js
> +                    append: "\n\n//# sourceURL=ImageViewer.webmodeler.js\n",
Done

2017-06-23 08:17 UTC, akileng56 commented on package.json
> +  "widgetName": "imageviewer",
Done

2017-06-23 08:17 UTC, akileng56 commented on package.json
> +  "description": "Display an image from specifed source",
Fixed

2017-06-23 08:17 UTC, akileng56 commented on package.json
> +    "emit": "tsc",
Removed

2017-06-23 08:18 UTC, akileng56 commented on package.json
> +    "url": "https://github.com/mendixlabs/slider"
Updated

2017-06-23 08:18 UTC, akileng56 commented on package.json
> +    "url": "https://github.com/mendixlabs/slider/issues"
Updated

2017-06-23 08:18 UTC, akileng56 commented on src/ImageViewer.xml
> +    <description>Change a number value using a slider</description>
Fixed

2017-06-23 08:19 UTC, akileng56 commented on src/ImageViewer.xml
> +            <description></description>
Fixed

2017-06-23 08:23 UTC, akileng56 commented on src/ImageViewer.xml
> +            </enumerationValues>
Fixed

2017-06-23 08:23 UTC, akileng56 commented on src/ImageViewer.xml
> +            <caption>System image</caption>
Fixed

2017-06-23 08:23 UTC, akileng56 commented on src/ImageViewer.xml
> +        <property key="imageAttribute" type="attribute" required="false" isPath="optional" pathType="reference">
Fixed

2017-06-23 08:24 UTC, akileng56 commented on src/ImageViewer.xml
> +            <caption>Dynamic URL</caption>
Done

2017-06-23 08:24 UTC, akileng56 commented on src/ImageViewer.xml
> +        <property key="static_Url" type="string" required="false">
Done

2017-06-23 08:31 UTC, merged